### ISSUE TITLE
Question: Continuous deployment

### ISSUE THREAD

**Issue by bashbro** [shyim/example-shopware-docker-project#2]
Good day,

a friend and I are planing to use Shopware in production. We want to run it in a docker container and use an image from shopware, so we dont have to setup the whole system from scretch. We also only use shopware as a headless system, so we wont make any changes to the frontend at all. We only have a small custom plugin, which we need to ship with.

The problem: we are new to php, symfony and shopware itself, as we come from a different software stack. We are unsure about how to setup a continuous deployment in this regards.

To be concrete - and hopefully you guys can help us out - we have the following insecurities:
1. If shopware or any plugin that we are using (like paypal) needs an update, how do we achieve this? Do we manually set the version up in the `composer.json` and start a new deployment? Should we fork an repository like this one?
2. If we manually set a higher shopware version in the `composer.json` and successfully push a new version to our production container, how does the production database gets migrated, if the new shopware version comes along with database changes?
3. Can we actually fork this repository for upcoming changes?
4. Or are we running in a complete wrong direction and we shouldnt use docker at all for production? Should we buy a vServer and setup a `deployer` deployment?

We just dont want to run in a situation in which we crash our production setup by simply updating the shopware version.

I hope you guys can help us out!
Thank you very much and with best regards

**Comment by bashbro** [comment]
@shyim Could you maybe help us out with our issue?

**Comment by shyim** [comment]
Hey,

you should fork this or create a own shopware project 
```bash
composer create-project shopware/production <name>
cd <name>
composer require shopware/docker
```

then you should have the same result as this example.


To install/update an extension or Shopware, you change the composer.json run `composer update` and rebuild the image. The entrypoint of the container checks the state and updates Shopware or installs / updates the extensions. so you don't have to do something here.

**Comment by bashbro** [comment]
@shyim 
Thank you very much! You helped us out a lot :) We got a working container now!
