### ISSUE TITLE
Strange behaviour after deployment

### ISSUE THREAD

**Issue by 8a53ecac** [shyim/example-shopware-docker-project#3]
Hello. I've tested the approach and noticed a few strange things. Certain plugins are not loaded correctly. 

Below is an error that is thrown when the admin UI calls api/_action/extension/refresh. 
(added the plugin (pre build) via composer req frosh/platform-thumbnail-processor)

```
The class "Frosh\ThumbnailProcessor\FroshPlatformThumbnailProcessor" is not found. Probably an class loader error. Check your plugin composer.json

{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Attempted to load class \u0022ThumbnailService\u0022 from namespace \u0022Frosh\\ThumbnailProcessor\\DependencyInjection\u0022.\nDid you forget a \u0022use\u0022 statement for \u0022Shopware\\Core\\Content\\Media\\Thumbnail\\ThumbnailService\u0022?"}]}
```

Similar messages were also displayed when trying to activate certain plugins manually via admin UI.

Especially with the FroshPlatformThumbnailProcessor plugin I tested it a bit more and reinstalled it several times. Most of the time it came back to the same problem, but once it didn't and the plugin started to work. But I could not get the plugin to work again with other clean installations.

I could also observe that certain scripts are presumably not loaded into the storefront. I haven't analysed it in detail yet, but it happens, for example, that product images are not displayed in the storefront, but in the admin UI or the Amazon Pay Button doesn't appear although it should.

The problems occur regardless of whether docker volumes or an object stoarage is used.
Occurs on 6.4.5.1 and 6.5.6.0.

What could be the reason that the plugins / assets? are not loaded correctly?

**Comment by shyim** [comment]
I think @stefanpoensgen solved that problem with ThumbnailService as the plugin right now does a really hacky way.

**Comment by stefanpoensgen** [comment]
```
#Dockerfile
RUN --mount=type=secret,id=composer_auth,dst=/src/auth.json \
    --mount=type=cache,target=/root/.composer \
    --mount=type=cache,target=/root/.npm \
    /usr/local/bin/entrypoint.sh shopware-cli project ci /src && \
    bin/ci -q --env=prod && \
    composer dump-autoload --classmap-authoritative --no-dev
```
Replace the `RUN` part within the Dockerfile

**Comment by 8a53ecac** [comment]
Thanks for pointing this out, it seems that the plugin works with these additions.
